# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-21 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadchat',
            name='inviter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='threadchat',
            name='remover',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='threadmember',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threadmembers', to='message.Thread'),
        ),
    ]
