# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20160422_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='purpose',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
