# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_auto_20160516_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='purpose_type',
            field=models.IntegerField(choices=[(0, b'General'), (1, b'Care')], default=0),
        ),
    ]
