# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_thread_purpose_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='purpose',
            field=models.TextField(default=b'', max_length=500, null=True),
        ),
    ]
