# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_auto_20160531_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='gender',
            field=models.IntegerField(choices=[(0, b'Female'), (1, b'Male'), (2, b'Other')], default=0),
        ),
        migrations.AddField(
            model_name='thread',
            name='hobbies',
            field=models.TextField(default=b'', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thread',
            name='notes',
            field=models.TextField(default=b'', max_length=500, null=True),
        ),
    ]
