# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_auto_20160615_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='gender',
            field=models.IntegerField(choices=[(0, b'Other'), (1, b'Female'), (2, b'Male')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='hours',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
