# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-23 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('first', models.CharField(blank=True, max_length=35, null=True)),
                ('last', models.CharField(blank=True, max_length=35, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('stripe_customer_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CareGiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hireable', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('certs', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
        ),
    ]
