# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-11 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
