# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20160517_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareSeeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True)),
                ('team_name', models.CharField(max_length=100)),
                ('mission', models.CharField(max_length=200)),
                ('main_phone', models.CharField(max_length=20)),
                ('website', models.CharField(max_length=100)),
                ('video', models.FileField(max_length=200, upload_to=b'')),
                ('email', models.FileField(max_length=200, upload_to=b'')),
                ('caregiver_needs', models.CharField(max_length=200)),
                ('hoyer_lift', models.BooleanField(default=False)),
                ('cough_assist', models.BooleanField(default=False)),
                ('adaptive_utensil', models.BooleanField(default=False)),
                ('meal_prep', models.BooleanField(default=False)),
                ('housekeeping', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
        ),
    ]
