# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_careseeker'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='background_verified',
            field=models.BooleanField(default=False),
        ),
    ]
