# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20160623_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careseeker',
            name='email',
            field=models.FileField(max_length=200, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='careseeker',
            name='main_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='careseeker',
            name='video',
            field=models.FileField(max_length=200, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='careseeker',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
