# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 19:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20160623_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careseeker',
            name='team_name',
            field=models.CharField(default=datetime.datetime(2016, 6, 23, 19, 14, 22, 542928, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
