# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20160624_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiver',
            name='about',
        ),
        migrations.AddField(
            model_name='caregiver',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='certs',
            field=models.CharField(choices=[('LPN', 'Licensed Practical Nurse (LPN)'), ('CNA', 'Certified Nursing Aide (CNA)'), ('IHA', 'In-Home Assistant) (IHA)'), ('HCS', 'Home Care Specialist (HCS)'), ('AD', 'Alzheimers & Dementia (AD)')], max_length=3),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='headline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='careseeker',
            name='email',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='careseeker',
            name='main_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='careseeker',
            name='video',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=b''),
        ),
    ]
