# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20160630_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careseeker',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
