# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20160912_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
