# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-28 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_account_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='offlineID_verified',
            field=models.BooleanField(default=False),
        ),
    ]
