# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-29 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_caregiver_offlineid_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careseeker',
            name='adaptive_utensil',
        ),
        migrations.RemoveField(
            model_name='careseeker',
            name='cough_assist',
        ),
        migrations.RemoveField(
            model_name='careseeker',
            name='housekeeping',
        ),
        migrations.RemoveField(
            model_name='careseeker',
            name='hoyer_lift',
        ),
        migrations.RemoveField(
            model_name='careseeker',
            name='meal_prep',
        ),
        migrations.AlterField(
            model_name='careseeker',
            name='caregiver_needs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
