# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-29 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20160929_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiver',
            name='offlineID_verified',
        ),
    ]
