application: humanlink-frontend
version: 1-2
runtime: python27
api_version: 1
threadsafe: true

env_variables:
  BACKEND: http://eb.humanlink.co
  #BACKEND: http://192.168.99.100:8080
  GAE_USE_SOCKETS_HTTPLIB: true

handlers:

  # Versioned asset files in the form of:
  # x.v-y.zz => x.z
- url: /static/(.*?\.)(v-.+)?(css|js)$
  static_files: static/\1\3
  upload: static/.*\.(css|js)$

- url: /images
  static_dir: assets/images

- url: /views/(.*)/partials/(.*)
  static_files: views/\1/partials/\2
  upload: views/.*/partials/.*

- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /.*
  script: main.app
  secure: always

libraries:

# OpenSSL.
- name: ssl
  version: latest

skip_files:
# Default settings.
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
# Custom.
- ^app$
- ^assets/stylesheets/less$
- ^bin$
- ^bower_components$
- ^node_modules$
- ^(.*/)?.*\.less$
- ^venv$
