# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20160421_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='kind',
            field=models.IntegerField(choices=[(0, b'User'), (1, b'Org')], default=0),
        ),
        migrations.AlterField(
            model_name='thread',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_org_id', to='org.Org'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='privacy',
            field=models.IntegerField(choices=[(0, b'Open'), (1, b'Closed'), (3, b'Members')], default=1, null=True),
        ),
    ]
