# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-19 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
