# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-21 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
